package mio68.lab.spring.jpa.basics.entity;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Data
@Entity // required for Entity
public class Customer { // must be top-level class, must be not final, can't be enum or interface

    //No-args constructor is required (Here it's generated by Lombok)

    @Id // primary key is required for an Entity
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id; // persistent final methods or persistent final instance variables are not allowed
    private String name;
    private String email;

}
